apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/app-sre/gitlab-project-exporter?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "25"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: gitlab-project-exporter-main
    appstudio.openshift.io/component: gitlab-project-exporter-main
    pipelines.appstudio.openshift.io/type: build
  name: gitlab-project-exporter-main-on-push
  namespace: app-sre-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/app-sre-tenant/gitlab-project-exporter-main/gitlab-project-exporter-main:{{revision}}
  - name: dockerfile
    value: Dockerfile
  - name: path-context
    value: .
  - name: target-stage
    value: prod
  pipelineRef:
    params:
    - name: url
      value: https://github.com/app-sre/shared-pipelines
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/multi-arch-build-pipeline.yaml
    resolver: git
  taskRunTemplate:
    serviceAccountName: build-pipeline-gitlab-project-exporter-main
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
